### PR TITLE
pids: remove hardcoded unmanaged provider name

### LINKED ISSUE #285: pids: deposit form error validation
**Identifier value**
When sending a wrong value for an identifier the API will answer with an error for the field `pids`. This error is:

- Does not appear in the list of fields shown at the top of the deposit form.
- Does not highlight in red the `identifiers` field.

Note that due to Marshmallow validation flows, the API reports errors for the gloabl `pids` field. There is only one use case when the full `pids.{scheme}.value.identifier` is given back; which still contains an extra `value` in the middle. More info in this PR https://github.com/inveniosoftware/invenio-rdm-records/pull/578 (See also comments in the code).

**Alternate identifier**
Adding an invalid identifier in alternate identifiers reports “Unknown field”

### PR DESCRIPTION
**Pull request by ntarocco**
* refers to inveniosoftware/invenio-rdm-records#580
 * closes #285
 * closes https://github.com/inveniosoftware/invenio-rdm-records/issues/763

### CODE REVIEW

**Comment by ntarocco** [comment]
Screenshot 2021-06-24 at 17 41 15

**Comment by ntarocco** [comment]
@jrcastro2 can you please review this PR?

**Review by jrcastro2 — COMMENTED** [review]
Overall LGTM.
There is just a small bug that needs to be fixed, when saving a wrong DOI and then clicking the "No" radio button for DOI I would expect to save it without a DOI, instead it still saves the previous DOI and the error message is still visible.

https://user-images.githubusercontent.com/15194802/123663108-5e7cc180-d836-11eb-84c1-6dbb1d20fb43.mp4

**Comment by ntarocco** [comment]
> Overall LGTM.
> There is just a small bug that needs to be fixed, when saving a wrong DOI and then clicking the "No" radio button for DOI I would expect to save it without a DOI, instead it still saves the previous DOI and the error message is still visible.
> pid-bug.mp4

Thanks a lot for taking the time of checking it out and testing it. I have simply removed the error from the `Managed` part because it does not make sense in this case. We will see if we need errors there, but it should not be the case.

**Review by jrcastro2 — APPROVED** [review]
Now the error message doesn't appear but it seems that there are still some bugs concerning the DOI, I presume this can be fixed in a separated issue:
- If you paste a DOI and click NO it still saves the previous one (I would expect nothing to be saved)
- If you paste a DOI, then delete it and try to save it, the UI breaks.

https://user-images.githubusercontent.com/15194802/124292825-466ab200-db56-11eb-9f06-996c2b6106bc.mp4

**Pull request closed without merging**
